name: Pushes NextJS image to ECR and deploys to ECS
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    env:
      REDIS_URL: ${{ secrets.REDIS_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tag env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: sa-east-1

      - name: Upload changes to S3 and issue Cloudfront invalidations
        uses: vladcosorg/action-s3-cloudfront-smart-deploy@v1
        with:
          source: public/content
          target: s3://maika-assets/content/
          distribution: EXCKAK1JLK0UE

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sistema-maika-repository
          TAG_NAME: ${{ env.RELEASE_VERSION }}
        run: |
          docker build \
            --build-arg REDIS_URL=${REDIS_URL} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG_NAME .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG_NAME

      - name: Render Amazon ECS task definition
        id: render-web-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .github/workflows/task-definition.json
          container-name: web-app
          image: ${{ steps.login-ecr.outputs.registry }}/sistema-maika-repository:${{ env.RELEASE_VERSION }}
          environment-variables: |
            REDIS_URL=${{ secrets.REDIS_URL }}
            AZURE_AD_TENANT_ID=${{ secrets.AZURE_AD_TENANT_ID }}
            AZURE_AD_CLIENT_SECRET=${{ secrets.AZURE_AD_CLIENT_SECRET }}
            AZURE_AD_CLIENT_ID=${{ secrets.AZURE_AD_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            S3_PUBLIC_KEY=${{ secrets.AWS_ACCESS_KEY }}
            S3_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-web-container.outputs.task-definition }}
          service: web-app
          cluster: sistema-maika-cluster
