name: Push the Docker image to AWS ECR Repo
on:
  push:
    branches:
      - main
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest

    env:
      MONGODB_URL: ${{ secrets.MONGODB_URL }}
      MONGODB_PASS: ${{ secrets.MONGODB_PASS }}
      REDIS_URL: ${{ secrets.REDIS_URL }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: sa-east-1

      - name: Upload changes to S3 and issue Cloudfront invalidations
        uses: vladcosorg/action-s3-cloudfront-smart-deploy@v1
        with:
          source: public/content
          target: s3://maika-assets/content/
          distribution: EXCKAK1JLK0UE

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push the image to ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: sistema-maika-repository
          IMAGE_TAG: ${{github.ref_name}}
        run: |
          docker build \
            --build-arg MONGODB_PASS=${MONGODB_PASS} \
            --build-arg MONGODB_URL=${MONGODB_URL} \
            --build-arg REDIS_URL=${REDIS_URL} \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
